language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- cd functions
- npm install
- npm run lint
- npm run test
- cd ..
deploy:
  provider: firebase
  edge: true
  project: beerxp-prd
  force: true
  token:
    secure: dYE/IuWhx7MCAndw10PldDjWVsCSj+NIjCS29FnRgXYFNey9rOQfS9Ggj0IgpPocvno5smfh2XIzV+ExB2mVgLrP8g/geIkLgSwkPuuCPB7+/efePaCv/kFMJ6aH+OCo2NzhzlCFILg4+Y3aUhd5m55liQqzrQL1G3CXzzMgRyTX6Ny95/ClVYRsJmTz/cNhQzxD1ypUzVWB2BUebbSMDbfFZhlW3Tr3brvKztXeX/ffqZaMjQhcTQuWYn9+yw5UktUiBJ7q2rotz/CHqgQ3TqTLC8W1ZH7d1+xvlTqDKohFXqzUo33g6bS3b75Tqw2ufU0dH8oMgamhUoONtEikkcPRvxR2/r8xMf1MPq7YBK5Ylzth983OciC6lRbHUrqvomQLk1iE0n9FA287xOAwbWQZVa3P8bfuII0nOzMf2vShrM5nRKiLCciz5bZetP1T0xXMkZ6F8f+xrUcLxQtUS8pDof4CGEagsFC9a9LcqkvidAA7eQdIDYBBvqRw/guXKyqXk+DE+DLi0x0Hs/8tqn3XDHjweEtO7lPSEFnWdKUP2Klt8DVMGbL7kZTXm371HE79hLJCDONDBYaVvM1x0tsB/QIFVMfWRBW/v+tDvmgVMPpN6F8kZG5dk5UOrZMSu5zqlxNOnjXeB6/YkYaSawFKhI92Ysx6UVuVGF30tEA=
notifications:
  slack:
    secure: pLDN9CBfbPTU+UzgHHNtza6Lk1YlyW3rltLMUmaj61HkBXs113FoaZNL4H5j3SMhiugksayvSaw/x9HvM5yCxXzN9hJ7NwvSg5MkkUtE20u3fcKa2//n8P+W2mXaKQuGt5M7PYSxZrGyozrEFsgVuUamIGBsV3QethaWacBl1tzApG5t6JRayc8B6+tjQNMSFc4+m7QtAalVgM3dbSE2//p4gKnJeHhMh9bBpXvxmdhDto89HYf1oBgdnTc+xEP3KSB/itBEPCLm/jYVkMi5gyGQC4ZzFGbJI9bocdbP6dYbRCyOWAwGyPw8cTeqhdh4MOW+gHuMknObE8+Ivgc16g6TfQyxhq2OLP3MuulxEuosC8i/nM/NK82SYR19xFeGPVvpYrTemF8ZUsx8ldqIzZivikgR3hqccVmy/HLnEOzYlKmfRX7iIH1rXCJ/FtF7LdKlIk0tZmbZ9TtZPsKt4u2GvoXCrKv/lK9H18EdS+F5Eb/jVvj7f9vHh+D90i200pCB1P6wetP1H/xSk1Q5zxFrkttuQc2NS4AySAVDEcbWgYIaqvoeUNp5k5GfhIOOyrM98AV5pHQ+GmMg0ZIcCukFCuQw3tX4P2qttjUzjZZvaJELH7L3JNtht3gE4tKTPjxWQ12wcSh5eNu+/5VWYPKCQyZdObRA8GmvdwD4ojQ=
