language: node_js
node_js:
    - node
branches:
    only:
        - master
script:
    - cd functions
    - npm install
    - npm run lint
    - npm run test
    - cd ..
deploy:
    provider: firebase
    edge: true
    project: beerxp
    force: true
    token:
        secure: J8caJwrfLwdtSYYgkYT+XAixCcPGUhvzLdirwfBa4ArtiWQW6ZwHTPcQfbxnq00C4vIZDHPEyj3DKVHQyuLd+QZ6puzxQFu3HQewdNqqP1UzwI74Mf0tKHSZtAztfMUw3H77duRtz1GVXZx7/G/Rqcmvv3YEpfqV02RkH3BQNA/6ZtXC2s/djVo+XrxZVajuu0udTDZlyY+EUeReU6IFipED8EU7vLPI6VJTR3/I6VM5rhtN8TkKJ0CPvLpYO+FFLarDXYYxXolH9E5RBYV5ZoWQXINBuo9CvhcU4a1i4qSnmA2lFL2iGwmCsjugb5hGTxVZ/7TvzCiFa2Hda722+cyYqRiyMDxzX4qVoPDw5WIkM2DT6yCzQPR4vQ41wQlUL4YTzZBSOgsEv5URmm1GwE/n8jGIFCnwt8LUzm5iGO/0xZ4kPLbiz+lR3dvJ/jzDL3WAZ+NXYC/fr1bnMPFckEj0r5rUkt5eFAa6rysEYaVDNhbjWq7nKZ0bRtCYGGUyCmSaDQMSOJlm+qwaiwgHGfRKYmY5imvfkA4FJzZWITzSH3IHnhrQFUxGYV0rtiBoKJZVv14syj4ptP/cIEWWwd6d55q9sJMWaD0ldBo04yNoZdsYaiGxx+Yn+WLdle2x/DrvCMPlrcCxzGNlD+TO9aOFkDqal+w6AjJZdyTUZSI=
notifications:
    slack:
        secure: pLDN9CBfbPTU+UzgHHNtza6Lk1YlyW3rltLMUmaj61HkBXs113FoaZNL4H5j3SMhiugksayvSaw/x9HvM5yCxXzN9hJ7NwvSg5MkkUtE20u3fcKa2//n8P+W2mXaKQuGt5M7PYSxZrGyozrEFsgVuUamIGBsV3QethaWacBl1tzApG5t6JRayc8B6+tjQNMSFc4+m7QtAalVgM3dbSE2//p4gKnJeHhMh9bBpXvxmdhDto89HYf1oBgdnTc+xEP3KSB/itBEPCLm/jYVkMi5gyGQC4ZzFGbJI9bocdbP6dYbRCyOWAwGyPw8cTeqhdh4MOW+gHuMknObE8+Ivgc16g6TfQyxhq2OLP3MuulxEuosC8i/nM/NK82SYR19xFeGPVvpYrTemF8ZUsx8ldqIzZivikgR3hqccVmy/HLnEOzYlKmfRX7iIH1rXCJ/FtF7LdKlIk0tZmbZ9TtZPsKt4u2GvoXCrKv/lK9H18EdS+F5Eb/jVvj7f9vHh+D90i200pCB1P6wetP1H/xSk1Q5zxFrkttuQc2NS4AySAVDEcbWgYIaqvoeUNp5k5GfhIOOyrM98AV5pHQ+GmMg0ZIcCukFCuQw3tX4P2qttjUzjZZvaJELH7L3JNtht3gE4tKTPjxWQ12wcSh5eNu+/5VWYPKCQyZdObRA8GmvdwD4ojQ=
