language: node_js

node_js:
    - node

branches:
    only:
        - master

before_script:
    - npm install -g firebase-tools
    - npm install -g preact-cli
    - npm install

script:
    - preact build

after_success:
    - firebase deploy --non-interactive --project="beerxp-prd" --token $FIREBASE_TOKEN --force

notifications:
    slack:
        secure: v12TkY5GbqQkWkV6YY7+mz2Oemv0jjNLHMYodWkkOxGbia8FrzM15qKR8Vts8XqB1SEoAH1llfiwyI4towqUcJG3tpLB/udpyib8onLPKjX3WL3qMXdQWKdAqSwfVvYjvpp6gHBVwSO8yi/D1gtxpmkLOrlMkWX29NhhNyprNfDOUfAa8eGZGBDR+/e7mtB6K+pKraR76paxeUnKZxvH57pDIJ1oTQz9SV0YKiql3IdKblfp3TciLjQ84IDcoIOydXhQuOIGSTgdteMWbBKc4SE3Gk3T45EvUuLwzAUaIC0pUa6vwtees0Daso9M+h7aqFMcwQR4s+Bg0RMdvy5h8WKgjn0oBlSGFldeQlHo4Nxn40gmZXvEMJEi3W9VF5Cc3j/U+KmQtTuc4CcbIATIedaqZl6qn2UBVtRCiUz+/meyFJSoV25m8qqVSBR/TGvdNXLHGuoG6g/Q9BJR4kfNo5GScr52aN46UQUlPShW1MNwAs8Gbf/4N+2DYCtTJBE0HbP00Ii8m+tNlV4CW8fxX2YxA462c/28nlrhqTcyiS9jMiBjGKFKtaRm9uF2esFfkx3HpvlFPcyiSxC+/1T2HVxJ5Apk5yccEkplbRy9j/tv6ocAnq/Du3TLGa0kfTNFP3GGkTJmiLX3yCJJFxRLua9sP0LDdMqQjl/h/OTsb9o=
