language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- cd functions
- npm install
- npm run lint
- npm run test
- cd ..
deploy:
  # provider: firebase
  # edge: false
  # project: beerxp-prd
  # force: true
  firebase deploy --non-interactive --project="beerxp-prd" --token=$token --force
  token:
    secure: dYE/IuWhx7MCAndw10PldDjWVsCSj+NIjCS29FnRgXYFNey9rOQfS9Ggj0IgpPocvno5smfh2XIzV+ExB2mVgLrP8g/geIkLgSwkPuuCPB7+/efePaCv/kFMJ6aH+OCo2NzhzlCFILg4+Y3aUhd5m55liQqzrQL1G3CXzzMgRyTX6Ny95/ClVYRsJmTz/cNhQzxD1ypUzVWB2BUebbSMDbfFZhlW3Tr3brvKztXeX/ffqZaMjQhcTQuWYn9+yw5UktUiBJ7q2rotz/CHqgQ3TqTLC8W1ZH7d1+xvlTqDKohFXqzUo33g6bS3b75Tqw2ufU0dH8oMgamhUoONtEikkcPRvxR2/r8xMf1MPq7YBK5Ylzth983OciC6lRbHUrqvomQLk1iE0n9FA287xOAwbWQZVa3P8bfuII0nOzMf2vShrM5nRKiLCciz5bZetP1T0xXMkZ6F8f+xrUcLxQtUS8pDof4CGEagsFC9a9LcqkvidAA7eQdIDYBBvqRw/guXKyqXk+DE+DLi0x0Hs/8tqn3XDHjweEtO7lPSEFnWdKUP2Klt8DVMGbL7kZTXm371HE79hLJCDONDBYaVvM1x0tsB/QIFVMfWRBW/v+tDvmgVMPpN6F8kZG5dk5UOrZMSu5zqlxNOnjXeB6/YkYaSawFKhI92Ysx6UVuVGF30tEA=
notifications:
  slack:
    secure: v12TkY5GbqQkWkV6YY7+mz2Oemv0jjNLHMYodWkkOxGbia8FrzM15qKR8Vts8XqB1SEoAH1llfiwyI4towqUcJG3tpLB/udpyib8onLPKjX3WL3qMXdQWKdAqSwfVvYjvpp6gHBVwSO8yi/D1gtxpmkLOrlMkWX29NhhNyprNfDOUfAa8eGZGBDR+/e7mtB6K+pKraR76paxeUnKZxvH57pDIJ1oTQz9SV0YKiql3IdKblfp3TciLjQ84IDcoIOydXhQuOIGSTgdteMWbBKc4SE3Gk3T45EvUuLwzAUaIC0pUa6vwtees0Daso9M+h7aqFMcwQR4s+Bg0RMdvy5h8WKgjn0oBlSGFldeQlHo4Nxn40gmZXvEMJEi3W9VF5Cc3j/U+KmQtTuc4CcbIATIedaqZl6qn2UBVtRCiUz+/meyFJSoV25m8qqVSBR/TGvdNXLHGuoG6g/Q9BJR4kfNo5GScr52aN46UQUlPShW1MNwAs8Gbf/4N+2DYCtTJBE0HbP00Ii8m+tNlV4CW8fxX2YxA462c/28nlrhqTcyiS9jMiBjGKFKtaRm9uF2esFfkx3HpvlFPcyiSxC+/1T2HVxJ5Apk5yccEkplbRy9j/tv6ocAnq/Du3TLGa0kfTNFP3GGkTJmiLX3yCJJFxRLua9sP0LDdMqQjl/h/OTsb9o=
